"""merge artist profile fields into user model

Revision ID: 12b7c03d0d38
Revises: ebd8c15092e3
Create Date: 2026-03-15 16:02:58.771442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b7c03d0d38'
down_revision: Union[str, Sequence[str], None] = 'ebd8c15092e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('instagram_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('twitter_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'language')
    op.drop_column('users', 'website_url')
    op.drop_column('users', 'twitter_url')
    op.drop_column('users', 'instagram_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
