"""fix_id_types_to_string_with_prefixes

Revision ID: 2900b45c0b56
Revises: 7adb32d04927
Create Date: 2026-03-10 15:29:33.927017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2900b45c0b56'
down_revision: Union[str, Sequence[str], None] = '7adb32d04927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_payment_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('preferred_method', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_code', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('paypal_email', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('follows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('follower_id', sa.String(), nullable=True),
    sa.Column('artist_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('is_monetized_stream', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plays_id'), 'plays', ['id'], unique=False)
    op.drop_index(op.f('ix_payout_requests_id'), table_name='payout_requests')
    op.drop_table('payout_requests')
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_garage_clips_id'), table_name='garage_clips')
    op.drop_table('garage_clips')
    op.drop_table('artist_profiles')
    op.drop_index(op.f('ix_lyrics_id'), table_name='lyrics')
    op.drop_table('lyrics')
    op.add_column('albums', sa.Column('cover_image', sa.String(), nullable=True))
    op.add_column('albums', sa.Column('description', sa.String(), nullable=True))
    op.add_column('albums', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.add_column('albums', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('albums', 'artist_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_albums_id'), 'albums', ['id'], unique=False)
    op.add_column('tracks', sa.Column('audio_path', sa.String(), nullable=False))
    op.add_column('tracks', sa.Column('cover_path', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('plays', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('two_factor_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), server_default='false', nullable=True))
    op.alter_column('users', 'total_earned_vcoins',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('users', 'vcoin_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'vcoin_balance',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_earned_vcoins',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('users', 'two_factor_secret')
    op.drop_column('users', 'verification_code')
    op.drop_column('tracks', 'likes')
    op.drop_column('tracks', 'plays')
    op.drop_column('tracks', 'cover_path')
    op.drop_column('tracks', 'audio_path')
    op.drop_index(op.f('ix_albums_id'), table_name='albums')
    op.alter_column('albums', 'artist_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('albums', 'created_at')
    op.drop_column('albums', 'release_date')
    op.drop_column('albums', 'description')
    op.drop_column('albums', 'cover_image')
    op.create_table('lyrics',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('lyrics_pkey')),
    sa.UniqueConstraint('track_id', name=op.f('lyrics_track_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_lyrics_id'), 'lyrics', ['id'], unique=False)
    op.create_table('artist_profiles',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stage_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('artist_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('artist_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('garage_clips',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('caption', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('garage_clips_pkey'))
    )
    op.create_index(op.f('ix_garage_clips_id'), 'garage_clips', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_table('payout_requests',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='payoutstatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payout_requests_pkey'))
    )
    op.create_index(op.f('ix_payout_requests_id'), 'payout_requests', ['id'], unique=False)
    op.drop_index(op.f('ix_plays_id'), table_name='plays')
    op.drop_table('plays')
    op.drop_table('likes')
    op.drop_table('follows')
    op.drop_table('artist_payment_settings')
    # ### end Alembic commands ###
