"""create fanlinks table

Revision ID: 29d0da2d3655
Revises: a3d772dea7e0
Create Date: 2026-07-16 13:11:59.317154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # <-- Import dialect for UUID support[cite: 4]

# revision identifiers, used by Alembic.
revision: str = '29d0da2d3655'
down_revision: Union[str, Sequence[str], None] = 'a3d772dea7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('fanlinks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    # Change these to postgresql.UUID to match albums.id and tracks.id[cite: 4]
    sa.Column('track_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('album_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('streaming_links', sa.JSON(), nullable=True),
    sa.Column('is_tipping_enabled', sa.Boolean(), nullable=True),
    sa.Column('vibe_gate_type', sa.String(), nullable=True),
    sa.Column('vibe_gate_value', sa.String(), nullable=True),
    sa.Column('views_count', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_fanlinks_slug'), 'fanlinks', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fanlinks_slug'), table_name='fanlinks')
    op.drop_table('fanlinks')
    # ### end Alembic commands ###