"""add albums table

Revision ID: 325320d6c1c6
Revises: dd3c90556cd5
Create Date: 2025-12-25 14:37:36.164794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325320d6c1c6'
down_revision: Union[str, Sequence[str], None] = 'dd3c90556cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'description')
    # ### end Alembic commands ###
