"""add monetization fields

Revision ID: 6b291a4a062c
Revises: b5655d3af257
Create Date: 2026-03-05 05:42:59.579513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b291a4a062c'
down_revision: Union[str, Sequence[str], None] = 'b5655d3af257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_profiles')
    op.add_column('plays', sa.Column('is_monetized_stream', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('monetization_eligible', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('total_earned_vcoins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_earned_vcoins')
    op.drop_column('users', 'monetization_eligible')
    op.drop_column('plays', 'is_monetized_stream')
    op.create_table('artist_profiles',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stage_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('artist_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('artist_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('artist_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
