"""add_monetization_and_purchases

Revision ID: d067dde42c01
Revises: 39a9c667d7d8
Create Date: 2026-03-13 20:02:23.181381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd067dde42c01'
down_revision: Union[str, Sequence[str], None] = '39a9c667d7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tracks', sa.Column('is_for_sale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'is_for_sale')
    op.drop_column('tracks', 'price')
    # ### end Alembic commands ###
