"""fanlink modifications

Revision ID: dc83d7c901f0
Revises: 536397ba0048
Create Date: 2026-07-18 14:47:10.735562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc83d7c901f0'
down_revision: Union[str, Sequence[str], None] = '536397ba0048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted to keep only fanlink changes ###
    op.create_table('fan_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('streaming_links', sa.JSON(), nullable=True),
    sa.Column('accept_tips', sa.Boolean(), nullable=True),
    sa.Column('subaccount_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fan_links_id'), 'fan_links', ['id'], unique=False)
    op.create_index(op.f('ix_fan_links_slug'), 'fan_links', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted to keep only fanlink changes ###
    op.drop_index(op.f('ix_fan_links_slug'), table_name='fan_links')
    op.drop_index(op.f('ix_fan_links_id'), table_name='fan_links')
    op.drop_table('fan_links')
    # ### end Alembic commands ###