"""added lyrics and clips

Revision ID: ef71d3155f6d
Revises: 6b291a4a062c
Create Date: 2026-03-05 16:00:39.404431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef71d3155f6d'
down_revision: Union[str, Sequence[str], None] = '6b291a4a062c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance_ngn', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('vcoin_balance', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('subscription_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_verified_artist', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_fee_paid', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('verification_amount_paid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_amount_paid')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'verification_fee_paid')
    op.drop_column('users', 'is_verified_artist')
    op.drop_column('users', 'subscription_expiry')
    op.drop_column('users', 'vcoin_balance')
    op.drop_column('users', 'balance_ngn')
    # ### end Alembic commands ###
